import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { AppHeader, Card, EmptyState, PrimaryButton, SectionTitle, StudyScreen, colors } from "@/components/study/ui";
import { useStudy } from "@/lib/study/store";

export default function ManageQuestionsScreen() {
  const { data, addSubject, addChapter, renameSubject, renameChapter, deleteSubject, deleteChapter } = useStudy();
  const [newSubject, setNewSubject] = useState("");
  const [newChapter, setNewChapter] = useState("");
  const [selectedSubjectId, setSelectedSubjectId] = useState<string>();
  const [subjectEdit, setSubjectEdit] = useState("");
  const [chapterEditId, setChapterEditId] = useState<string>();
  const [chapterEdit, setChapterEdit] = useState("");
  const activeSubjectId = selectedSubjectId ?? data.subjects[0]?.id;
  const activeSubject = data.subjects.find((subject) => subject.id === activeSubjectId);
  const activeChapters = data.chapters.filter((chapter) => chapter.subjectId === activeSubjectId);
  useEffect(() => { setSubjectEdit(activeSubject?.name ?? ""); }, [activeSubject?.id, activeSubject?.name]);
  const createSubject = () => { const id = addSubject(newSubject); if (!id) { Alert.alert("Add a subject name", "For example, বাংলা, English, or গণিত."); return; } setSelectedSubjectId(id); setNewSubject(""); };
  const createChapter = () => { if (!activeSubjectId) { Alert.alert("Choose a subject first", "Create or choose a subject before adding a chapter."); return; } const id = addChapter(activeSubjectId, newChapter); if (!id) { Alert.alert("Add a chapter name", "For example, Grammar or Linear Equation."); return; } setNewChapter(""); };
  const saveSubject = () => { if (!activeSubjectId || !renameSubject(activeSubjectId, subjectEdit)) Alert.alert("Could not rename", "Use a new non-empty subject name."); };
  const saveChapter = (id: string) => { if (!renameChapter(id, chapterEdit)) Alert.alert("Could not rename", "Use a new non-empty chapter name."); setChapterEditId(undefined); };
  const removeSubject = (id: string, name: string) => Alert.alert(`Delete ${name}?`, "All chapters and questions inside it will also be deleted.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => { deleteSubject(id); if (activeSubjectId === id) setSelectedSubjectId(undefined); } }]);
  const removeChapter = (id: string, name: string) => Alert.alert(`Delete ${name}?`, "Its saved questions will be removed from this device.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => deleteChapter(id) }]);
  return <StudyScreen><AppHeader title="Manage Questions" subtitle="Add, rename, or remove your local question bank" back={() => router.back()} />
    <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><SectionTitle>Subjects</SectionTitle><Card><TextInput value={newSubject} onChangeText={setNewSubject} placeholder="New subject name" placeholderTextColor="#8D9AAF" style={styles.input} returnKeyType="done" onSubmitEditing={createSubject} /><View style={{ marginTop: 10 }}><PrimaryButton label="Add Subject" icon="add" onPress={createSubject} /></View></Card>{data.subjects.length ? <><View style={styles.chips}>{data.subjects.map((subject) => <Pressable key={subject.id} onPress={() => setSelectedSubjectId(subject.id)} style={({ pressed }) => [styles.chip, activeSubjectId === subject.id && styles.chipActive, pressed && styles.pressed]}><Text style={[styles.chipText, activeSubjectId === subject.id && styles.chipTextActive]}>{subject.name}</Text></Pressable>)}</View>{activeSubject ? <Card><Text style={styles.fieldLabel}>Selected subject</Text><TextInput value={subjectEdit} onChangeText={setSubjectEdit} style={styles.input} placeholderTextColor="#8D9AAF" /><View style={styles.actionRow}><PrimaryButton label="Rename" variant="secondary" icon="edit" onPress={saveSubject} /><PrimaryButton label="Delete" variant="danger" icon="delete-outline" onPress={() => removeSubject(activeSubject.id, activeSubject.name)} /></View></Card> : null}</> : <EmptyState icon="auto-stories" title="No subjects yet" detail="Create one here or import questions to create it automatically." />}
      <SectionTitle>Chapters</SectionTitle><Card><TextInput value={newChapter} onChangeText={setNewChapter} placeholder={activeSubjectId ? "New chapter name" : "Choose a subject first"} placeholderTextColor="#8D9AAF" editable={Boolean(activeSubjectId)} style={styles.input} returnKeyType="done" onSubmitEditing={createChapter} /><View style={{ marginTop: 10 }}><PrimaryButton label="Add Chapter" icon="add" onPress={createChapter} disabled={!activeSubjectId} /></View></Card>{activeSubjectId && activeChapters.length ? <View style={styles.chapterList}>{activeChapters.map((chapter) => { const count = data.questions.filter((question) => question.chapterId === chapter.id).length; const editing = chapterEditId === chapter.id; return <Card key={chapter.id} style={styles.chapterCard}><View style={styles.chapterIcon}><MaterialIcons name="topic" size={20} color={colors.blue} /></View><View style={{ flex: 1 }}>{editing ? <TextInput value={chapterEdit} onChangeText={setChapterEdit} style={styles.inlineInput} autoFocus returnKeyType="done" onSubmitEditing={() => saveChapter(chapter.id)} /> : <><Text style={styles.chapterName}>{chapter.name}</Text><Text style={styles.chapterMeta}>{count} question{count === 1 ? "" : "s"}</Text></>}</View>{editing ? <Pressable accessibilityRole="button" onPress={() => saveChapter(chapter.id)} style={styles.iconButton}><MaterialIcons name="check" size={20} color={colors.success} /></Pressable> : <Pressable accessibilityRole="button" onPress={() => { setChapterEditId(chapter.id); setChapterEdit(chapter.name); }} style={styles.iconButton}><MaterialIcons name="edit" size={18} color={colors.blue} /></Pressable>}<Pressable accessibilityRole="button" accessibilityLabel={`Delete ${chapter.name}`} onPress={() => removeChapter(chapter.id, chapter.name)} style={styles.iconButton}><MaterialIcons name="delete-outline" size={20} color={colors.error} /></Pressable></Card>; })}</View> : activeSubjectId ? <Text style={styles.noChapters}>No chapters yet for this subject.</Text> : null}</ScrollView>
  </StudyScreen>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 34, gap: 12 }, input: { height: 48, borderRadius: 12, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 13, color: colors.ink, fontSize: 15, backgroundColor: "#FCFDFE" }, inlineInput: { height: 40, borderRadius: 10, borderWidth: 1, borderColor: "#B8D1FF", paddingHorizontal: 10, color: colors.ink, fontSize: 14, backgroundColor: colors.softBlue }, fieldLabel: { color: colors.muted, fontSize: 12, fontWeight: "700", marginBottom: 7 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { minHeight: 42, borderRadius: 12, borderColor: colors.border, borderWidth: 1, backgroundColor: colors.surface, paddingHorizontal: 12, justifyContent: "center" }, chipActive: { backgroundColor: colors.softBlue, borderColor: "#B8D1FF" }, chipText: { color: colors.ink, fontSize: 13, fontWeight: "700" }, chipTextActive: { color: colors.blue }, actionRow: { flexDirection: "row", gap: 10, marginTop: 10 }, chapterList: { gap: 8 }, chapterCard: { flexDirection: "row", alignItems: "center", gap: 8, padding: 13 }, chapterIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.softBlue, justifyContent: "center", alignItems: "center" }, chapterName: { color: colors.ink, fontSize: 15, fontWeight: "800" }, chapterMeta: { color: colors.muted, fontSize: 12, marginTop: 3 }, iconButton: { width: 36, height: 36, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: "#F5F8FC" }, noChapters: { color: colors.muted, fontSize: 13, textAlign: "center", marginTop: 3 }, pressed: { opacity: 0.68 } });
