import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { AppHeader, Card, EmptyState, PrimaryButton, SectionTitle, StudyScreen, colors } from "@/components/study/ui";
import { useStudy } from "@/lib/study/store";

export default function ManageQuestionsScreen() {
  const { data, addSubject, addChapter, deleteSubject, deleteChapter } = useStudy();
  const [subjectName, setSubjectName] = useState("");
  const [chapterName, setChapterName] = useState("");
  const [selectedSubjectId, setSelectedSubjectId] = useState<string>();
  const activeSubjectId = selectedSubjectId ?? data.subjects[0]?.id;
  const activeChapters = data.chapters.filter((chapter) => chapter.subjectId === activeSubjectId);
  const createSubject = () => { const id = addSubject(subjectName); if (!id) { Alert.alert("Add a subject name", "For example, বাংলা, English, or গণিত."); return; } setSelectedSubjectId(id); setSubjectName(""); };
  const createChapter = () => { if (!activeSubjectId) { Alert.alert("Choose a subject first", "Create or choose a subject before adding a chapter."); return; } const id = addChapter(activeSubjectId, chapterName); if (!id) { Alert.alert("Add a chapter name", "For example, Grammar or Linear Equation."); return; } setChapterName(""); };
  const removeSubject = (id: string, name: string) => Alert.alert(`Delete ${name}?`, "Its chapters and questions will be removed from this device.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => { deleteSubject(id); if (activeSubjectId === id) setSelectedSubjectId(undefined); } }]);
  const removeChapter = (id: string, name: string) => Alert.alert(`Delete ${name}?`, "Its saved questions will be removed from this device.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => deleteChapter(id) }]);
  return <StudyScreen><AppHeader title="Manage Questions" subtitle="Keep your offline question bank organized" back={() => router.back()} />
    <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><SectionTitle>Subjects</SectionTitle><Card><TextInput value={subjectName} onChangeText={setSubjectName} placeholder="New subject name" placeholderTextColor="#8D9AAF" style={styles.input} returnKeyType="done" onSubmitEditing={createSubject} /><View style={{ marginTop: 10 }}><PrimaryButton label="Add Subject" icon="add" onPress={createSubject} /></View></Card>{data.subjects.length ? <View style={styles.chips}>{data.subjects.map((subject) => <View key={subject.id} style={[styles.subjectChip, activeSubjectId === subject.id && styles.subjectChipSelected]}><Pressable onPress={() => setSelectedSubjectId(subject.id)} style={({ pressed }) => [styles.chipButton, pressed && styles.pressed]}><Text style={[styles.chipText, activeSubjectId === subject.id && styles.chipTextSelected]}>{subject.name}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Delete ${subject.name}`} onPress={() => removeSubject(subject.id, subject.name)} style={({ pressed }) => [styles.chipDelete, pressed && styles.pressed]}><MaterialIcons name="close" size={16} color={activeSubjectId === subject.id ? colors.blue : colors.muted} /></Pressable></View>)}</View> : <EmptyState icon="auto-stories" title="No subjects yet" detail="Create one here or import questions to create it automatically." />}
      <SectionTitle>Chapters</SectionTitle><Card><TextInput value={chapterName} onChangeText={setChapterName} placeholder={activeSubjectId ? "New chapter name" : "Choose a subject first"} placeholderTextColor="#8D9AAF" editable={Boolean(activeSubjectId)} style={styles.input} returnKeyType="done" onSubmitEditing={createChapter} /><View style={{ marginTop: 10 }}><PrimaryButton label="Add Chapter" icon="add" onPress={createChapter} disabled={!activeSubjectId} /></View></Card>{activeSubjectId && activeChapters.length ? <View style={styles.chapterList}>{activeChapters.map((chapter) => { const count = data.questions.filter((question) => question.chapterId === chapter.id).length; return <Card key={chapter.id} style={styles.chapterCard}><View style={styles.chapterIcon}><MaterialIcons name="topic" size={20} color={colors.blue} /></View><View style={{ flex: 1 }}><Text style={styles.chapterName}>{chapter.name}</Text><Text style={styles.chapterMeta}>{count} question{count === 1 ? "" : "s"}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`Delete ${chapter.name}`} onPress={() => removeChapter(chapter.id, chapter.name)} style={({ pressed }) => [styles.deleteButton, pressed && styles.pressed]}><MaterialIcons name="delete-outline" size={20} color={colors.error} /></Pressable></Card>; })}</View> : activeSubjectId ? <Text style={styles.noChapters}>No chapters yet for this subject.</Text> : null}</ScrollView>
  </StudyScreen>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 34, gap: 12 }, input: { height: 48, borderRadius: 12, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 13, color: colors.ink, fontSize: 15, backgroundColor: "#FCFDFE" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, subjectChip: { maxWidth: "100%", minHeight: 42, borderRadius: 12, borderColor: colors.border, borderWidth: 1, backgroundColor: colors.surface, flexDirection: "row", alignItems: "center", overflow: "hidden" }, subjectChipSelected: { backgroundColor: colors.softBlue, borderColor: "#B8D1FF" }, chipButton: { paddingLeft: 12, paddingVertical: 10 }, chipDelete: { paddingVertical: 10, paddingHorizontal: 8 }, chipText: { color: colors.ink, fontSize: 13, fontWeight: "700" }, chipTextSelected: { color: colors.blue }, chapterList: { gap: 8 }, chapterCard: { flexDirection: "row", alignItems: "center", gap: 10, padding: 13 }, chapterIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.softBlue, justifyContent: "center", alignItems: "center" }, chapterName: { color: colors.ink, fontSize: 15, fontWeight: "800" }, chapterMeta: { color: colors.muted, fontSize: 12, marginTop: 3 }, deleteButton: { width: 38, height: 38, borderRadius: 12, backgroundColor: "#FFF1F1", alignItems: "center", justifyContent: "center" }, noChapters: { color: colors.muted, fontSize: 13, textAlign: "center", marginTop: 3 }, pressed: { opacity: 0.68 } });
