import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppHeader, Card, EmptyState, PrimaryButton, StudyScreen, colors } from "@/components/study/ui";
import { useStudy } from "@/lib/study/store";

const dateLabel = (timestamp: number) => new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(timestamp));

export default function HistoryTab() {
  const { data } = useStudy();
  return <StudyScreen><AppHeader title="Exam History" subtitle={`${data.testHistory.length} saved exam${data.testHistory.length === 1 ? "" : "s"}`} right={<View style={styles.headerIcon}><MaterialIcons name="history" size={22} color={colors.blue} /></View>} />{data.testHistory.length ? <FlatList data={data.testHistory} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={`Open ${item.mode} result from ${dateLabel(item.completedAt)}`} onPress={() => router.push({ pathname: "/test/result", params: { testId: item.id } })} style={({ pressed }) => [pressed && styles.pressed]}><Card style={styles.historyCard}><View style={styles.cardTop}><View style={styles.modeBadge}><MaterialIcons name={item.mode === "mock" ? "edit-note" : "bolt"} size={17} color={item.mode === "mock" ? colors.blue : colors.coral} /><Text style={[styles.modeText, { color: item.mode === "mock" ? colors.blue : colors.coral }]}>{item.mode === "mock" ? "Mock Test" : "Flash Test"}</Text></View><Text style={styles.date}>{dateLabel(item.completedAt)}</Text></View><View style={styles.scoreRow}><View><Text style={styles.score}>{item.correctCount}/{item.questionIds.length}</Text><Text style={styles.scoreLabel}>সঠিক উত্তর</Text></View><View style={styles.accuracy}><Text style={styles.accuracyValue}>{item.questionIds.length ? Math.round((item.correctCount / item.questionIds.length) * 100) : 0}%</Text><Text style={styles.scoreLabel}>নির্ভুলতা</Text></View><MaterialIcons name="chevron-right" size={24} color={colors.muted} /></View><View style={styles.stats}><Stat label="সঠিক" value={item.correctCount} color={colors.success} /><Stat label="ভুল" value={item.wrongCount} color={colors.error} /><Stat label="স্কিপ" value={item.skippedCount} color={colors.caution} /></View><Text style={styles.openHint}>Tap to review all answers</Text></Card></Pressable>} /> : <EmptyState icon="history" title="এখনও কোনো exam নেই" detail="Mock Test বা Flash Test শেষ করলে এখানে প্রতিটি result live save হবে।" action={<PrimaryButton label="Start a test" icon="edit-note" onPress={() => router.replace("/(tabs)/test")} />} />}</StudyScreen>;
}

function Stat({ label, value, color }: { label: string; value: number; color: string }) { return <View style={styles.stat}><Text style={[styles.statValue, { color }]}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({ headerIcon: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: colors.softBlue }, list: { padding: 14, paddingBottom: 30, gap: 10 }, historyCard: { padding: 14, borderRadius: 18 }, cardTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, modeBadge: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 10, backgroundColor: colors.softBlue }, modeText: { fontSize: 12, fontWeight: "900" }, date: { color: colors.muted, fontSize: 11 }, scoreRow: { flexDirection: "row", alignItems: "center", marginTop: 15 }, score: { color: colors.ink, fontSize: 28, fontWeight: "900" }, scoreLabel: { color: colors.muted, fontSize: 11, marginTop: 1 }, accuracy: { marginLeft: "auto", alignItems: "flex-end", marginRight: 10 }, accuracyValue: { color: colors.blue, fontSize: 22, fontWeight: "900" }, stats: { flexDirection: "row", gap: 26, marginTop: 14, paddingTop: 11, borderTopWidth: 1, borderTopColor: colors.border }, stat: { alignItems: "flex-start" }, statValue: { fontSize: 15, fontWeight: "900" }, statLabel: { color: colors.muted, fontSize: 10, marginTop: 2 }, openHint: { color: colors.blue, fontSize: 11, fontWeight: "800", marginTop: 12 }, pressed: { opacity: 0.7, transform: [{ scale: 0.985 }] },
});
