import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";

import { AppHeader, Card, EmptyState, Metric, PrimaryButton, SectionTitle, StudyScreen, colors } from "@/components/study/ui";
import { calculateProgress, chapterAccuracy, subjectAccuracy } from "@/lib/study/analytics";
import { useStudy } from "@/lib/study/store";

export default function ProgressTab() {
  const { data } = useStudy(); const progress = calculateProgress(data);
  if (!data.attempts.length) return <StudyScreen><AppHeader title="Progress" subtitle="Your learning story, kept simple" /><EmptyState icon="bar-chart" title="Progress will appear here" detail="Start your first test to see your progress." action={<PrimaryButton label="Go to Test" icon="edit-note" onPress={() => router.push("/(tabs)/test")} />} /></StudyScreen>;
  return <StudyScreen><AppHeader title="Progress" subtitle="Your learning story, kept simple" /><ScrollView contentContainerStyle={styles.content}><Card><Text style={styles.overline}>OVERALL</Text><View style={styles.metrics}><Metric value={progress.attempted} label="Attempted" /><Metric value={progress.correct} label="Correct" /><Metric value={`${progress.accuracy}%`} label="Accuracy" /><Metric value={progress.testsCompleted} label="Tests" /></View></Card><SectionTitle>Subject performance</SectionTitle><View style={styles.performanceList}>{data.subjects.map((subject) => <PerformanceRow key={subject.id} label={subject.name} value={subjectAccuracy(data, subject.id)} />)}</View><SectionTitle>Chapter performance</SectionTitle><View style={styles.performanceList}>{data.chapters.map((chapter) => <PerformanceRow key={chapter.id} label={chapter.name} value={chapterAccuracy(data, chapter.id)} />)}</View><SectionTitle>Test history</SectionTitle>{data.testHistory.length ? data.testHistory.slice(0, 8).map((test) => <Card key={test.id} style={styles.history}><View><Text style={styles.historyTitle}>{test.mode === "mock" ? "Mock Test" : "Flash Test"}</Text><Text style={styles.historyDate}>{new Date(test.completedAt).toLocaleDateString()}</Text></View><View style={styles.historyScore}><Text style={styles.score}>{test.correctCount}/{test.questionIds.length}</Text><Text style={styles.scoreLabel}>correct</Text></View></Card>) : <Card><Text style={styles.emptyHistory}>Your completed mock tests will appear here.</Text></Card>}</ScrollView></StudyScreen>;
}
function PerformanceRow({ label, value }: { label: string; value?: number }) { const state = value === undefined ? { label: "Not attempted", color: colors.muted } : value >= 80 ? { label: "Strong", color: colors.success } : value >= 60 ? { label: "Average", color: colors.caution } : { label: "Needs Practice", color: colors.error }; return <Card style={styles.performance}><View style={{ flex: 1 }}><View style={styles.performanceTop}><Text style={styles.performanceLabel}>{label}</Text><Text style={[styles.performanceValue, { color: state.color }]}>{value === undefined ? "—" : `${value}%`}</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${value ?? 0}%`, backgroundColor: state.color }]} /></View><Text style={[styles.state, { color: state.color }]}>{state.label}</Text></View></Card>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 32, gap: 12 }, overline: { color: colors.blue, fontSize: 11, fontWeight: "800", letterSpacing: 0.8, marginBottom: 14 }, metrics: { flexDirection: "row", gap: 8 }, performanceList: { gap: 8 }, performance: { padding: 14 }, performanceTop: { flexDirection: "row", justifyContent: "space-between", gap: 12 }, performanceLabel: { color: colors.ink, flex: 1, fontSize: 14, fontWeight: "800" }, performanceValue: { fontSize: 14, fontWeight: "800" }, track: { height: 7, borderRadius: 4, overflow: "hidden", backgroundColor: "#E8EDF3", marginTop: 10 }, fill: { height: "100%", borderRadius: 4 }, state: { fontSize: 11, fontWeight: "800", marginTop: 7 }, history: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, historyTitle: { color: colors.ink, fontSize: 15, fontWeight: "800" }, historyDate: { color: colors.muted, fontSize: 12, marginTop: 4 }, historyScore: { alignItems: "flex-end" }, score: { color: colors.blue, fontSize: 17, fontWeight: "800" }, scoreLabel: { color: colors.muted, fontSize: 11, marginTop: 2 }, emptyHistory: { color: colors.muted, textAlign: "center", fontSize: 13 } });
