import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { AppHeader, Card, EmptyState, PrimaryButton, StudyScreen, colors } from "@/components/study/ui";
import { useStudy } from "@/lib/study/store";

export default function QuestionListScreen() {
  const { chapterId } = useLocalSearchParams<{ chapterId: string }>();
  const { getChapter, getQuestions } = useStudy();
  const chapter = getChapter(chapterId);
  const [query, setQuery] = useState("");
  const questions = useMemo(() => getQuestions({ chapterId }), [chapterId, getQuestions]);
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase(); if (!needle) return questions; return questions.filter((question) => `${question.prompt} ${Object.values(question.options).join(" ")} ${question.explanation}`.toLocaleLowerCase().includes(needle)); }, [questions, query]);
  if (!chapter) return <StudyScreen><AppHeader title="Questions" back={() => router.back()} /><EmptyState title="Topic not found" detail="It may have been removed from this device." /></StudyScreen>;
  return <StudyScreen><AppHeader title={chapter.name} subtitle={`${questions.length} questions`} back={() => router.back()} right={<View style={styles.headerActions}><Pressable accessibilityRole="button" accessibilityLabel="Manage question bank" onPress={() => router.push("/questions/manage")} style={styles.headerIcon}><MaterialIcons name="settings" size={21} color={colors.ink} /></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Import questions" onPress={() => router.push("/questions/import")} style={styles.headerIcon}><MaterialIcons name="add" size={22} color={colors.ink} /></Pressable></View>} /><View style={styles.searchWrap}><MaterialIcons name="search" size={20} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search questions, options, or explanation" placeholderTextColor="#8D9AAF" style={styles.search} returnKeyType="search" /></View><FlatList data={filtered} keyExtractor={(item) => item.id} contentContainerStyle={[styles.list, !filtered.length && { flexGrow: 1 }]} showsVerticalScrollIndicator={false} ListEmptyComponent={questions.length ? <EmptyState icon="search-off" title="No matching questions" detail="Try another word or clear the search." action={<PrimaryButton label="Clear search" variant="secondary" onPress={() => setQuery("")} />} /> : <EmptyState title="No questions yet" detail="Import questions into this topic to start studying." action={<PrimaryButton label="Import Questions" icon="file-upload" onPress={() => router.push("/questions/import")} />} />} renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={`Open question ${item.serial}`} onPress={() => router.push({ pathname: "/questions/detail/[questionId]", params: { questionId: item.id } })} style={({ pressed }) => [pressed && styles.pressed]}><Card style={styles.questionCard}><View style={styles.cardTop}><View style={styles.typeBadge}><Text style={styles.typeText}>MCQ</Text></View><View style={styles.cardTopRight}><Text style={styles.serial}>Q{item.serial}</Text><MaterialIcons name="chevron-right" size={22} color={colors.muted} /></View></View><Text style={styles.breadcrumb}>{chapter.name} · Practice</Text><Text style={styles.question}>{item.prompt}</Text><View style={styles.options}>{Object.entries(item.options).filter(([, value]) => Boolean(value)).map(([key, value]) => <View key={key} style={styles.option}><View style={styles.optionKey}><Text style={styles.optionKeyText}>{key}</Text></View><Text style={styles.optionText}>{value}</Text></View>)}</View><Text style={styles.meta}>{Object.keys(item.options).length} options · Answer saved · {item.explanation === "Explanation unavailable" ? "No explanation" : "Explanation included"}</Text></Card></Pressable>} /></StudyScreen>;
}

const styles = StyleSheet.create({
  headerActions: { flexDirection: "row", gap: 7 }, headerIcon: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.emeraldBorder }, pressed: { opacity: 0.7, transform: [{ scale: 0.98 }] }, searchWrap: { marginHorizontal: 10, marginBottom: 7, minHeight: 46, borderRadius: 14, borderWidth: 1, borderColor: colors.emeraldBorder, backgroundColor: colors.glass, flexDirection: "row", alignItems: "center", paddingHorizontal: 13, gap: 8 }, search: { flex: 1, color: colors.ink, fontSize: 15, height: 44 }, list: { paddingHorizontal: 10, paddingBottom: 30, gap: 9 }, questionCard: { padding: 14, borderRadius: 18, borderTopWidth: 0, shadowOpacity: 0.04, elevation: 1 }, cardTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, cardTopRight: { flexDirection: "row", alignItems: "center", gap: 6 }, typeBadge: { paddingHorizontal: 11, paddingVertical: 7, borderRadius: 11, borderWidth: 1, borderColor: colors.emeraldBorder, backgroundColor: colors.softBlue }, typeText: { color: colors.blueDark, fontSize: 12, fontWeight: "900", letterSpacing: 1 }, serial: { color: colors.muted, fontSize: 12, fontWeight: "900" }, breadcrumb: { color: colors.muted, fontSize: 12, marginTop: 12 }, question: { color: colors.ink, fontSize: 18, lineHeight: 26, fontWeight: "900", marginTop: 10 }, options: { gap: 7, marginTop: 16 }, option: { minHeight: 47, flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 12, borderWidth: 1, borderColor: colors.emeraldBorder, backgroundColor: colors.glass, paddingHorizontal: 10, paddingVertical: 7 }, optionKey: { width: 29, height: 29, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: colors.softBlue }, optionKeyText: { color: colors.blueDark, fontSize: 12, fontWeight: "900" }, optionText: { flex: 1, color: colors.ink, fontSize: 14, lineHeight: 19 }, meta: { color: colors.muted, fontSize: 11, marginTop: 12 },
});
