import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { AppHeader, Card, PrimaryButton, SectionTitle, StudyScreen, colors } from "@/components/study/ui";
import { useStudy } from "@/lib/study/store";

const COUNTS = [5, 10, 20, 30];
const TIMES = [{ seconds: 0, label: "No limit" }, { seconds: 5 * 60, label: "5 min" }, { seconds: 10 * 60, label: "10 min" }, { seconds: 20 * 60, label: "20 min" }, { seconds: 30 * 60, label: "30 min" }];

export default function FlashSetupScreen() {
  const { data } = useStudy();
  const [subjectId, setSubjectId] = useState<string>();
  const [chapterId, setChapterId] = useState<string>();
  const [count, setCount] = useState(10);
  const [customCount, setCustomCount] = useState("");
  const [durationSeconds, setDurationSeconds] = useState(0);
  const chapters = useMemo(() => data.chapters.filter((chapter) => !subjectId || chapter.subjectId === subjectId), [data.chapters, subjectId]);
  const available = data.questions.filter((question) => (!subjectId || question.subjectId === subjectId) && (!chapterId || question.chapterId === chapterId));
  const requested = customCount.trim() ? Math.max(1, Number(customCount) || 1) : count;
  const start = () => { if (!available.length) { Alert.alert("No matching questions", "Choose a subject or chapter that has questions."); return; } router.replace({ pathname: "/test/flash", params: { subjectId: subjectId ?? "", chapterId: chapterId ?? "", count: String(Math.min(requested, available.length)), duration: String(durationSeconds) } }); };
  return <StudyScreen><AppHeader title="Flash Test" subtitle="Choose a quick practice set" back={() => router.back()} /><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><SectionTitle>Choose questions</SectionTitle><PickerCard title="Subject" items={[{ id: "all", label: "All subjects" }, ...data.subjects.map((item) => ({ id: item.id, label: item.name }))]} selected={subjectId ?? "all"} onSelect={(id) => { setSubjectId(id === "all" ? undefined : id); setChapterId(undefined); }} /><PickerCard title="Chapter" items={[{ id: "all", label: "All chapters" }, ...chapters.map((item) => ({ id: item.id, label: item.name }))]} selected={chapterId ?? "all"} onSelect={(id) => setChapterId(id === "all" ? undefined : id)} /><Text style={styles.available}>{available.length} question{available.length === 1 ? "" : "s"} available</Text><SectionTitle>Number of questions</SectionTitle><View style={styles.choices}>{COUNTS.map((value) => <Choice key={value} label={String(value)} active={!customCount && count === value} onPress={() => { setCount(value); setCustomCount(""); }} />)}<TextInput value={customCount} onChangeText={setCustomCount} placeholder="Custom" placeholderTextColor="#8D9AAF" keyboardType="number-pad" style={[styles.custom, customCount && styles.customActive]} /></View><SectionTitle>Time limit</SectionTitle><View style={styles.choices}>{TIMES.map((item) => <Choice key={item.seconds} label={item.label} active={durationSeconds === item.seconds} onPress={() => setDurationSeconds(item.seconds)} />)}</View><Card style={styles.summary}><Text style={styles.summaryTitle}>Quick practice set</Text><Text style={styles.summaryDetail}>{Math.min(requested, available.length || requested)} questions · {TIMES.find((item) => item.seconds === durationSeconds)?.label ?? "No limit"} · immediate feedback</Text></Card><PrimaryButton label="Start Flash Test" icon="bolt" onPress={start} disabled={!available.length} /></ScrollView></StudyScreen>;
}

function PickerCard({ title, items, selected, onSelect }: { title: string; items: { id: string; label: string }[]; selected: string; onSelect: (id: string) => void }) { return <Card><Text style={styles.fieldTitle}>{title}</Text><View style={styles.pickerRows}>{items.map((item) => <Pressable key={item.id} onPress={() => onSelect(item.id)} style={({ pressed }) => [styles.pickerRow, selected === item.id && styles.pickerActive, pressed && styles.pressed]}><View style={[styles.radio, selected === item.id && styles.radioActive]}>{selected === item.id ? <View style={styles.dot} /> : null}</View><Text style={[styles.pickerLabel, selected === item.id && styles.pickerLabelActive]}>{item.label}</Text></Pressable>)}</View></Card>; }
function Choice({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.choice, active && styles.choiceActive, pressed && styles.pressed]}><Text style={[styles.choiceText, active && styles.choiceTextActive]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 34, gap: 12 }, fieldTitle: { color: colors.ink, fontSize: 14, fontWeight: "800", marginBottom: 9 }, pickerRows: { gap: 3 }, pickerRow: { minHeight: 42, flexDirection: "row", gap: 10, alignItems: "center", paddingHorizontal: 8, borderRadius: 10 }, pickerActive: { backgroundColor: colors.softBlue }, radio: { width: 19, height: 19, borderRadius: 10, borderWidth: 1.5, borderColor: "#9BA9BC", alignItems: "center", justifyContent: "center" }, radioActive: { borderColor: colors.blue }, dot: { width: 9, height: 9, borderRadius: 5, backgroundColor: colors.blue }, pickerLabel: { color: colors.ink, fontSize: 14 }, pickerLabelActive: { color: colors.blue, fontWeight: "800" }, available: { color: colors.muted, fontSize: 12, marginTop: -2, paddingLeft: 3 }, choices: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, choice: { minHeight: 42, paddingHorizontal: 14, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, justifyContent: "center", alignItems: "center" }, choiceActive: { backgroundColor: colors.softBlue, borderColor: "#B8D1FF" }, choiceText: { color: colors.muted, fontSize: 13, fontWeight: "700" }, choiceTextActive: { color: colors.blue }, custom: { height: 42, width: 86, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, color: colors.ink, fontSize: 13, paddingHorizontal: 9, textAlign: "center" }, customActive: { borderColor: "#B8D1FF", backgroundColor: colors.softBlue }, summary: { backgroundColor: "#F5F9FF", borderColor: "#D5E4FF" }, summaryTitle: { color: colors.ink, fontSize: 16, fontWeight: "800" }, summaryDetail: { color: colors.muted, fontSize: 13, marginTop: 5 }, pressed: { opacity: 0.68 } });
