import * as Haptics from "expo-haptics";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Platform, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { AppHeader, Card, EmptyState, PrimaryButton, StudyScreen, colors } from "@/components/study/ui";
import { type AnswerKey } from "@/lib/study/types";
import { useStudy } from "@/lib/study/store";

export default function FlashTestScreen() {
  const { subjectId = "", chapterId = "", count = "10" } = useLocalSearchParams<{ subjectId?: string; chapterId?: string; count?: string }>();
  const { data, recordFlashAttempt } = useStudy();
  const [questionIds, setQuestionIds] = useState<string[]>([]);
  const [index, setIndex] = useState(0);
  const [selected, setSelected] = useState<AnswerKey>();
  const [correctCount, setCorrectCount] = useState(0);
  const [wrongCount, setWrongCount] = useState(0);
  const insets = useSafeAreaInsets();
  useEffect(() => { if (questionIds.length) return; const available = data.questions.filter((question) => (!subjectId || question.subjectId === subjectId) && (!chapterId || question.chapterId === chapterId)); const ids = [...available].sort(() => Math.random() - 0.5).slice(0, Math.max(1, Number(count) || 10)).map((question) => question.id); setQuestionIds(ids); }, [data.questions, subjectId, chapterId, count, questionIds.length]);
  const questions = useMemo(() => questionIds.map((id) => data.questions.find((question) => question.id === id)).filter(Boolean), [questionIds, data.questions]);
  const question = questions[index];
  if (!questionIds.length) return <StudyScreen><AppHeader title="Flash Test" back={() => router.back()} /><EmptyState icon="bolt" title="Preparing questions" detail="Your quick practice set is loading." /></StudyScreen>;
  if (index >= questions.length) { const total = correctCount + wrongCount; const accuracy = total ? Math.round((correctCount / total) * 100) : 0; return <StudyScreen><AppHeader title="Flash Result" subtitle="Quick practice complete" back={() => router.replace("/(tabs)/test")} /><View style={styles.resultWrap}><Card style={styles.resultCard}><Text style={styles.resultValue}>{accuracy}%</Text><Text style={styles.resultLabel}>accuracy</Text><View style={styles.resultStats}><Stat label="Correct" value={correctCount} color={colors.success} /><Stat label="Wrong" value={wrongCount} color={colors.error} /><Stat label="Total" value={total} color={colors.blue} /></View></Card><PrimaryButton label="Practice Again" icon="refresh" onPress={() => router.replace("/test/flash-setup")} /><PrimaryButton label="Back to Test" variant="secondary" icon="arrow-back" onPress={() => router.replace("/(tabs)/test")} /></View></StudyScreen>; }
  if (!question) return <StudyScreen><AppHeader title="Flash Test" back={() => router.back()} /><EmptyState icon="bolt" title="Add questions first" detail="Import questions to unlock quick practice." action={<PrimaryButton label="Import Questions" icon="file-upload" onPress={() => router.replace("/questions/import")} />} /></StudyScreen>;
  const choose = (key: AnswerKey) => { if (selected) return; setSelected(key); const correct = recordFlashAttempt(question.id, key); if (correct) setCorrectCount((value) => value + 1); else setWrongCount((value) => value + 1); if (Platform.OS !== "web") Haptics.notificationAsync(correct ? Haptics.NotificationFeedbackType.Success : Haptics.NotificationFeedbackType.Error); };
  const next = () => { if (index >= questions.length - 1) { setIndex(questions.length); return; } setIndex((value) => value + 1); setSelected(undefined); };
  const isCorrect = selected === question.correctOption;
  return <StudyScreen><AppHeader title="Flash Test" subtitle={`Question ${index + 1}/${questions.length} · ${correctCount} correct · ${wrongCount} wrong`} back={() => router.back()} />
    <View style={styles.page}><ScrollView style={styles.scroll} contentContainerStyle={styles.content}><View style={styles.progress}><View style={[styles.progressFill, { width: `${((index + 1) / questions.length) * 100}%` }]} /></View><Card><Text style={styles.question}>Q. {question.prompt}</Text><View style={styles.options}>{Object.entries(question.options).filter(([, value]) => Boolean(value)).map(([key, value]) => { const optionKey = key as AnswerKey; const chosen = selected === optionKey; const correctAnswer = Boolean(selected && optionKey === question.correctOption); return <Pressable key={key} disabled={Boolean(selected)} onPress={() => choose(optionKey)} style={({ pressed }) => [styles.option, chosen && (isCorrect ? styles.optionCorrect : styles.optionWrong), correctAnswer && styles.optionCorrect, pressed && !selected && styles.pressed]}><Text style={[styles.optionKey, (chosen || correctAnswer) && styles.optionKeyActive]}>{key}</Text><Text style={[styles.optionText, (chosen || correctAnswer) && styles.optionTextActive]}>{value}</Text></Pressable>; })}</View>{selected ? <View style={[styles.feedback, isCorrect ? styles.feedbackCorrect : styles.feedbackWrong]}><Text style={[styles.feedbackTitle, { color: isCorrect ? colors.success : colors.error }]}>{isCorrect ? "Correct!" : "Incorrect"}</Text><Text style={styles.feedbackText}>Correct answer: {question.correctOption}. {question.options[question.correctOption]}</Text><Text style={styles.feedbackExplanation}>{question.explanation}</Text></View> : null}</Card></ScrollView><View style={[styles.footer, { paddingBottom: Math.max(insets.bottom, 12) }]}><PrimaryButton label={selected ? (index >= questions.length - 1 ? "See Result" : "Next Question") : "Choose an answer"} icon={selected ? "arrow-forward" : "touch-app"} onPress={() => { if (selected) next(); }} disabled={!selected} /><Text style={styles.footerHint}>{selected ? "Your answer is ready. Continue when you are ready." : "Choose one option above to continue."}</Text></View></View>
  </StudyScreen>;
}
function Stat({ label, value, color }: { label: string; value: number; color: string }) { return <View style={styles.stat}><Text style={[styles.statValue, { color }]}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ page: { flex: 1 }, scroll: { flex: 1 }, content: { padding: 20, paddingBottom: 18, gap: 14 }, footer: { backgroundColor: colors.surface, borderTopWidth: 1, borderTopColor: colors.border, paddingHorizontal: 20, paddingTop: 12 }, footerHint: { color: colors.muted, textAlign: "center", fontSize: 11, lineHeight: 16, marginTop: 7 }, progress: { height: 5, overflow: "hidden", borderRadius: 4, backgroundColor: "#DDE5F0" }, progressFill: { height: "100%", borderRadius: 4, backgroundColor: colors.blue }, question: { color: colors.ink, fontSize: 18, lineHeight: 27, fontWeight: "800", flexShrink: 1 }, options: { marginTop: 22, gap: 10 }, option: { minHeight: 58, borderRadius: 13, borderWidth: 1, borderColor: colors.border, backgroundColor: "#FCFDFE", flexDirection: "row", alignItems: "flex-start", gap: 12, paddingHorizontal: 12, paddingVertical: 12 }, optionCorrect: { borderColor: "#A8DFC4", backgroundColor: "#F1FBF6" }, optionWrong: { borderColor: "#F2BFBF", backgroundColor: "#FFF4F4" }, optionKey: { width: 27, height: 27, flexShrink: 0, marginTop: 1, borderRadius: 9, backgroundColor: "#EEF2F7", color: colors.muted, textAlign: "center", lineHeight: 27, fontSize: 13, fontWeight: "800" }, optionKeyActive: { backgroundColor: colors.blue, color: "#FFFFFF" }, optionText: { color: colors.ink, fontSize: 16, flex: 1, flexShrink: 1, minWidth: 0, lineHeight: 23, paddingTop: 1 }, optionTextActive: { fontWeight: "700" }, feedback: { marginTop: 18, borderRadius: 13, padding: 14 }, feedbackCorrect: { backgroundColor: "#F1FBF6" }, feedbackWrong: { backgroundColor: "#FFF4F4" }, feedbackTitle: { fontSize: 17, fontWeight: "800" }, feedbackText: { color: colors.ink, fontSize: 13, lineHeight: 19, marginTop: 5 }, feedbackExplanation: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 7 }, resultWrap: { flex: 1, padding: 20, gap: 12 }, resultCard: { alignItems: "center", backgroundColor: "#F5F9FF", borderColor: "#D5E4FF", paddingVertical: 28 }, resultValue: { color: colors.blue, fontSize: 36, fontWeight: "800" }, resultLabel: { color: colors.muted, fontSize: 12, fontWeight: "700", marginTop: 3 }, resultStats: { width: "100%", flexDirection: "row", justifyContent: "space-around", marginTop: 22, paddingTop: 15, borderTopWidth: 1, borderTopColor: "#D5E4FF" }, stat: { alignItems: "center" }, statValue: { fontSize: 18, fontWeight: "800" }, statLabel: { color: colors.muted, fontSize: 11, marginTop: 3 }, pressed: { opacity: 0.7 } });
